WAN-UPM-PER03:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
WAN-SKL-PER03:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
WAN-UPM-PER02:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
V3:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
WAN-SKL-PER01:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
V30:
        - TestBgpNeighborSession
        - TestBgpNeighborCount
        - TestBgpNeighborCountDown
        - TestIsisAdjacency
        - TestIsisAdjacencyCount
        - TestBfdSessionCount
        - TestBfdPeerSession
        - TestChassisAlarm
        - TestSystemAlarm
        - TestRouteStatic
        - TestRouteDirect
        - TestRouteLocal
        - TestRouteRsvp
        - TestRouteBgp
        - TestRouteIsis
